workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
      vars:
        APP_NAME: "sweeterdreamsiOS1"
    scripts:
      # -------------------------------------------------------
      # Install XcodeGen (using Homebrew — recommended method)
      # -------------------------------------------------------
      - name: Install XcodeGen
        script: |
          brew update
          brew install xcodegen

      # -------------------------------------------------------
      # Generate Xcode project
      # -------------------------------------------------------
      - name: Run XcodeGen
        script: |
          xcodegen generate

      # -------------------------------------------------------
      # Install CocoaPods if your project needs it (optional)
      # If you have a Podfile, leave this. If not, remove it.
      # -------------------------------------------------------
      - name: Install CocoaPods
        script: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          else
            echo "No Podfile found, skipping pods"
          fi

      # -------------------------------------------------------
      # Build the app (archive)
      # -------------------------------------------------------
      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace "${APP_NAME}.xcworkspace" \
            -scheme "${APP_NAME}" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/${APP_NAME}.xcarchive \
            archive | xcpretty

      # -------------------------------------------------------
      # Export IPA
      # -------------------------------------------------------
      - name: Export IPA
        script: |
          xcodebuild
