workflows:
  build-and-export-ios:
    name: Debug + Build iOS with XcodeGen
    max_build_duration: 30
    environment:
      xcode: latest

    scripts:

      # --------------------------------------------
      # 1. Debug directories + detect wrong project.yml
      # --------------------------------------------
      - name: Debug directories and project.yml
        script: |
          echo "================= DIRECTORY DEBUG ================="
          echo "PWD (current working directory):"
          pwd
          echo
          echo "CM_BUILD_DIR (Codemagic repo checkout dir):"
          echo "$CM_BUILD_DIR"
          echo
          echo "CM_SOURCE_DIR:"
          echo "$CM_SOURCE_DIR"
          echo
          echo "Listing PWD:"
          ls -A .
          echo
          echo "Searching entire workspace for ANY project.yml/project.yaml:"
          find / -maxdepth 6 -type f \( -name "project.yml" -o -name "project.yaml" \) 2>/dev/null
          echo "===================================================="
          echo
          echo ">>>> Forcing cd into CM_BUILD_DIR"
          cd "$CM_BUILD_DIR"
          echo "Now in:"
          pwd
          echo
          echo "Repo root contents:"
          ls -A .
          echo
          echo "==== project.yml (visible whitespace) ===="
          cat -A project.yml || echo "!!! No project.yml found here !!!"
          echo "=========================================="
          echo


      # --------------------------------------------
      # 2. Install XcodeGen
      # --------------------------------------------
      - name: Install XcodeGen
        script: |
          echo "Installing XcodeGen..."
          brew install xcodegen || true
          echo "XcodeGen version:"
          xcodegen --version
          echo


      # --------------------------------------------
      # 3. Generate Xcode project
      # --------------------------------------------
      - name: Generate Xcode project
        script: |
          echo "Generating project…"
          cd "$CM_BUILD_DIR"
          echo "Running XcodeGen from:"
          pwd
          echo
          xcodegen generate
          echo
          echo "Generated files:"
          ls -R .
          echo


      # --------------------------------------------
      # 4. Build for device (unsigned)
      # --------------------------------------------
      - name: Build for device (unsigned)
        script: |
          cd "$CM_BUILD_DIR"
          echo "Building..."
          set -o pipefail
          PROJECT=$(ls *.xcodeproj | head -n 1)
          echo "Detected project: $PROJECT"
          if [ -z "$PROJECT" ]; then
            echo "ERROR: XcodeGen did not generate a project."
            exit 1
          fi
          SCHEME=$(basename "$PROJECT" .xcodeproj)
          echo "Using scheme: $SCHEME"

          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build


    # --------------------------------------------
    # 5. Artifacts
    # --------------------------------------------
    artifacts:
      - $CM_BUILD_DIR/**/*.app
