workflows:
  build-and-export-ios:
    name: Build iOS unsigned (.ipa) using XcodeGen
    max_build_duration: 30
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen || true
      - name: Generate Xcode project
        script: |
          set -e
          xcodegen generate
          echo "Generated files:"
          ls -R .
      - name: Build for device (unsigned)
        script: |
          set -o pipefail
          PROJECT=$(ls *.xcodeproj | head -n 1)
          echo "Detected project: $PROJECT"
          if [ -z "$PROJECT" ]; then
            echo "ERROR: XcodeGen did not generate a project."
            exit 1
          fi
          SCHEME=$(basename "$PROJECT" .xcodeproj)
          echo "Using scheme: $SCHEME"
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
      - name: Package as .ipa
        script: |
          set -e
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*Release-iphoneos" -prune -print 2>/dev/null | head -n 1)
          if [ -z "$APP_PATH" ]; then
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" | head -n 1)
          fi
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: .app bundle not found."
            exit 1
          fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r SweeterDreams.ipa Payload
          mv SweeterDreams.ipa SweeterDreams.ipa
    artifacts:
      - SweeterDreams.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
