name: SweeterDreams

options:
  bundleIdPrefix: com.example
  minimumXcodeGenVersion: 2.38.0

configs:
  Debug: debug
  Release: release

settings:
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  SWIFT_VERSION: "5.0"

targets:
  SweeterDreams:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources/HealthExportKit
    resources:
      - path: Resources
    info:
      path: Resources/Info.plist
    entitlements:
      path: Resources/HealthExportKit.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.sweeterdreams
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO
      DEVELOPMENT_TEAM: ""

schemes:
  SweeterDreams:
    build:
      targets:
        - SweeterDreams
    run:
      config: Debug
    archive:
      config: Release
