name: SweeterDreams
options:
  bundleIdPrefix: com.example

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  SweeterDreams:
    type: application
    platform: iOS
    deploymentTarget: "16.0"   # change if you want lower/higher
    sources:
      - Sources/SweeterDreams
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    info:
      path: Sources/SweeterDreams/Info.plist
    schemes:
      - name: SweeterDreams
        shared: true
